name: "Deploy Actions Test"

on:
    push:
        branches: ["main"]

jobs:
    deploy-actions-testing:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hacemos pull del codigo"
            - run: echo "Correr migraciones"
            - run: echo "Generar binario"
            - run: echo "Publicar version"